# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

hostname: "2357625c.ngrok.io"

applicationID: "364832813973056"
accessToken: "EAAFL0EJHfkABAPFQbz9ulpUZBqT0DEjbLbOEOPoa9CYLk5iGM0RqHUHnlIZAaxBwl0gVux6s2HsEzIz8rNLYo2IBv2BSZCPE4z8LOh7AvJF7hyN31KUZAifOL4OvKZCj93zL4IVZB4kykCI4AZCQsTY92yHOf7J91RsD0t4gfW4YAZDZD"
appSecret: "15dda2d31234e5b24f5f72dcbca2fede"

verifyToken: "I love Unicorns"

displayGetStarted: true
# greetingMessage: ""

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

targetAudience: openToAll
targetAudienceOpenToSome: ""
targetAudienceCloseToSome: ""

trustedDomains: []
autoRespondGetStarted: true

paymentTesters: []

chatExtensionHomeUrl: ""
chatExtensionInTest: true
chatExtensionShowShareButton: false

enabled: true
